/*
 Navicat Premium Data Transfer

 Source Server         : 本地
 Source Server Type    : PostgreSQL
 Source Server Version : 180003 (180003)
 Source Host           : localhost:5432
 Source Catalog        : system_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 180003 (180003)
 File Encoding         : 65001

 Date: 13/03/2026 00:03:00
*/


-- ----------------------------
-- Sequence structure for a_employee_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."a_employee_id_seq";
CREATE SEQUENCE "public"."a_employee_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for a_menu_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."a_menu_id_seq";
CREATE SEQUENCE "public"."a_menu_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for a_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."a_user_id_seq";
CREATE SEQUENCE "public"."a_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for org_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."org_id_seq";
CREATE SEQUENCE "public"."org_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for a_employee
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_employee";
CREATE TABLE "public"."a_employee" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of a_employee
-- ----------------------------

-- ----------------------------
-- Table structure for a_goods
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_goods";
CREATE TABLE "public"."a_goods" (
  "id" int4 NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default",
  "create_time" timestamp(0) NOT NULL,
  "is_deleted" int2 NOT NULL DEFAULT 0
)
;

-- ----------------------------
-- Records of a_goods
-- ----------------------------

-- ----------------------------
-- Table structure for a_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_menu";
CREATE TABLE "public"."a_menu" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "create_time" timestamp(0) NOT NULL DEFAULT now(),
  "code" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "is_deleted" int2 NOT NULL DEFAULT 0,
  "menu_type" int2 NOT NULL,
  "parent_id" int4,
  "url" varchar(100) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."a_menu"."name" IS '菜单名';
COMMENT ON COLUMN "public"."a_menu"."menu_type" IS '菜单类型';
COMMENT ON COLUMN "public"."a_menu"."parent_id" IS '父级菜单';

-- ----------------------------
-- Records of a_menu
-- ----------------------------
INSERT INTO "public"."a_menu" VALUES (2, '库存管理', '2026-03-08 00:17:52', 'INVENTORY_MANAGE', 0, 1, NULL, NULL);
INSERT INTO "public"."a_menu" VALUES (3, '销售管理', '2026-03-08 00:19:34', 'SALE_MANAGE', 0, 1, NULL, NULL);
INSERT INTO "public"."a_menu" VALUES (4, '财务管理', '2026-03-08 00:21:36', 'FINANCE_MANAGE', 0, 1, NULL, NULL);
INSERT INTO "public"."a_menu" VALUES (7, '权限管理', '2026-03-10 22:10:51', 'PERMISSION_MANAGE', 0, 2, 5, NULL);
INSERT INTO "public"."a_menu" VALUES (8, '基础类型管理', '2026-03-10 22:20:03', 'TYPE_MANAGE', 0, 2, 5, NULL);
INSERT INTO "public"."a_menu" VALUES (9, '系统基础设置', '2026-03-10 22:20:47', 'BASE_SETTING', 0, 2, 5, NULL);
INSERT INTO "public"."a_menu" VALUES (5, '基础数据', '2026-03-10 22:09:33', 'SETTING', 0, 1, NULL, NULL);
INSERT INTO "public"."a_menu" VALUES (10, '供应商', '2026-03-12 22:13:06', 'SUPPLIER', 0, 2, 1, NULL);
INSERT INTO "public"."a_menu" VALUES (11, '采购订单', '2026-03-12 22:13:24', 'PURCHASE_ORDER', 0, 2, 1, NULL);
INSERT INTO "public"."a_menu" VALUES (12, '入库', '2026-03-12 22:14:04', 'STORE', 0, 2, 1, NULL);
INSERT INTO "public"."a_menu" VALUES (13, '付款', '2026-03-12 22:14:40', 'PAYMENT', 0, 2, 1, NULL);
INSERT INTO "public"."a_menu" VALUES (14, '客户', '2026-03-12 22:18:46', 'CUSTOMER', 0, 3, 3, NULL);
INSERT INTO "public"."a_menu" VALUES (15, '销售订单', '2026-03-12 22:20:00', 'SALE_ORDER', 0, 3, 3, NULL);
INSERT INTO "public"."a_menu" VALUES (16, '发货', '2026-03-12 22:31:09', 'SEND_OUT', 0, 3, 3, NULL);
INSERT INTO "public"."a_menu" VALUES (17, '收款', '2026-03-12 22:34:50', 'RECEIVE_PAYMENT', 0, 3, 3, NULL);
INSERT INTO "public"."a_menu" VALUES (1, '采购管理', '2026-03-08 00:11:01', 'PUTCHASE_MANAGE', 0, 1, NULL, '/');
INSERT INTO "public"."a_menu" VALUES (6, '组织机构管理', '2026-03-10 22:10:03', 'ORG_MANAGE', 0, 2, 5, '/organization');

-- ----------------------------
-- Table structure for a_org
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_org";
CREATE TABLE "public"."a_org" (
  "id" int4 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "parent_id" int4,
  "leader_id" int4,
  "leader_name" varchar(255) COLLATE "pg_catalog"."default",
  "leader_mobile" varchar(11) COLLATE "pg_catalog"."default",
  "tel" varchar(12) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of a_org
-- ----------------------------

-- ----------------------------
-- Table structure for a_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_role";
CREATE TABLE "public"."a_role" (
  "id" int4 NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "create_time" timestamp(0) NOT NULL,
  "is_deleted" int2 NOT NULL
)
;
COMMENT ON COLUMN "public"."a_role"."name" IS '权限名';

-- ----------------------------
-- Records of a_role
-- ----------------------------

-- ----------------------------
-- Table structure for a_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."a_user";
CREATE TABLE "public"."a_user" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "username" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "realname" varchar(50) COLLATE "pg_catalog"."default",
  "create_time" timestamp(0) NOT NULL,
  "is_deleted" int2 NOT NULL DEFAULT 0,
  "status" int2 NOT NULL DEFAULT 1
)
;
COMMENT ON COLUMN "public"."a_user"."username" IS '账号';
COMMENT ON COLUMN "public"."a_user"."password" IS '密码';
COMMENT ON COLUMN "public"."a_user"."realname" IS '真实姓名';

-- ----------------------------
-- Records of a_user
-- ----------------------------
INSERT INTO "public"."a_user" VALUES (1, 'administrators', '111111', '系统管理员', '2026-03-06 00:00:00', 0, 1);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."a_employee_id_seq"
OWNED BY "public"."a_employee"."id";
SELECT setval('"public"."a_employee_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."a_menu_id_seq"
OWNED BY "public"."a_menu"."id";
SELECT setval('"public"."a_menu_id_seq"', 17, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."a_user_id_seq"
OWNED BY "public"."a_user"."id";
SELECT setval('"public"."a_user_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."org_id_seq"
OWNED BY "public"."a_org"."id";
SELECT setval('"public"."org_id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for a_employee
-- ----------------------------
SELECT setval('"public"."a_employee_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table a_employee
-- ----------------------------
ALTER TABLE "public"."a_employee" ADD CONSTRAINT "a_employee_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table a_goods
-- ----------------------------
ALTER TABLE "public"."a_goods" ADD CONSTRAINT "goods_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for a_menu
-- ----------------------------
SELECT setval('"public"."a_menu_id_seq"', 17, true);

-- ----------------------------
-- Primary Key structure for table a_menu
-- ----------------------------
ALTER TABLE "public"."a_menu" ADD CONSTRAINT "menu_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for a_org
-- ----------------------------
SELECT setval('"public"."org_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table a_org
-- ----------------------------
ALTER TABLE "public"."a_org" ADD CONSTRAINT "org_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table a_role
-- ----------------------------
ALTER TABLE "public"."a_role" ADD CONSTRAINT "role_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for a_user
-- ----------------------------
SELECT setval('"public"."a_user_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table a_user
-- ----------------------------
ALTER TABLE "public"."a_user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");
